"""Offline PostgreSQL dialect, connection lifecycle, isolation and serverless checks."""
import importlib.util
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

import psycopg
from fastapi.testclient import TestClient

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "backend"))
from app.config import Settings, settings
from app.main import app
from app.services import storage
from app.services.contract_analysis import analyze_contract
from app.services.security import get_current_user
from test_contract_analysis import source


class PostgresStorageTests(unittest.TestCase):
    def setUp(self):
        storage._migrated_databases.clear()
        self.addCleanup(storage._migrated_databases.clear)

    def fake_connection(self):
        factory = MagicMock()
        raw = factory.return_value.__enter__.return_value
        return factory, raw

    def test_configuration_is_private_and_blank_defaults_to_sqlite(self):
        with patch.dict(os.environ, {"DATABASE_URL": ""}):
            config = Settings(_env_file=None)
            self.assertEqual(config.database_url, "")
        config = Settings(_env_file=None, database_url="postgresql://synthetic-secret@test.invalid/database")
        self.assertNotIn("synthetic-secret", repr(config))
        with tempfile.TemporaryDirectory() as folder, patch.object(settings, "database_url", ""), \
             patch.object(settings, "storage_path", Path(folder) / "nested" / "sqlite.db"), \
             patch.object(storage.psycopg, "connect") as connect:
            with storage.connection() as conn:
                conn.execute("INSERT INTO users VALUES (?, ?, ?, ?, ?)", ("id", "synthetic", "hash", "now", 0))
            self.assertEqual(storage.get_user_by_id("id").email, "synthetic")
            connect.assert_not_called()

    def test_postgres_placeholders_keep_parameters_separate(self):
        raw = MagicMock()
        conn = storage.PostgresConnection(raw)
        value = "synthetic ? '); DROP TABLE users;--"
        conn.execute("SELECT email FROM users WHERE id=? AND email=?", ("id", value))
        raw.execute.assert_called_once_with("SELECT email FROM users WHERE id=%s AND email=%s", ("id", value))

    def test_postgres_migrations_use_bytea_safe_columns_and_identity(self):
        raw = MagicMock()
        storage._run_migrations(storage.PostgresConnection(raw))
        queries = [call.args[0] for call in raw.execute.call_args_list]
        self.assertTrue(any("pdf BYTEA NOT NULL" in q for q in queries))
        self.assertTrue(any("GENERATED BY DEFAULT AS IDENTITY" in q for q in queries))
        self.assertFalse(any("PRAGMA" in q or " BLOB " in q for q in queries))
        self.assertTrue(all("IF NOT EXISTS" in q for q in queries))
        self.assertTrue(any("FOREIGN KEY (user_id) REFERENCES users(id)" in q for q in queries))

    def test_connection_commit_close_timeouts_pool_compatibility_and_migration_cache(self):
        factory, raw = self.fake_connection()
        url = "postgresql://synthetic:test@test.invalid/database"
        with patch.object(settings, "database_url", url), patch.object(storage.psycopg, "connect", factory), \
             patch.object(storage, "_run_migrations") as migrate:
            for _ in range(2):
                with storage.connection() as conn:
                    self.assertIsInstance(conn, storage.PostgresConnection)
                    conn.execute("SELECT ?", (1,))
            self.assertEqual(migrate.call_count, 1)
            self.assertEqual(raw.commit.call_count, 1)  # Schema transaction committed separately.
            self.assertEqual(factory.return_value.__exit__.call_count, 2)  # psycopg commits/closes operation transactions.
            factory.assert_called_with(url, connect_timeout=settings.database_connect_timeout, prepare_threshold=None)
            settings_queries = [c for c in raw.execute.call_args_list if "set_config" in c.args[0]]
            self.assertEqual(len(settings_queries), 3)
            self.assertTrue(all("true" in c.args[0] for c in settings_queries))
            self.assertTrue(any("pg_advisory_xact_lock" in c.args[0] for c in raw.execute.call_args_list))

    def test_exception_rolls_back_and_does_not_fall_back_to_sqlite(self):
        factory, _ = self.fake_connection()
        with patch.object(settings, "database_url", "postgresql://synthetic"), \
             patch.object(storage.psycopg, "connect", factory), patch.object(storage, "_run_migrations"), \
             patch.object(storage.sqlite3, "connect") as sqlite:
            with self.assertRaises(RuntimeError):
                with storage.connection():
                    raise RuntimeError("synthetic operation failure")
            self.assertIs(factory.return_value.__exit__.call_args.args[0], RuntimeError)
            sqlite.assert_not_called()
        with patch.object(settings, "database_url", "postgresql://synthetic"), \
             patch.object(storage.psycopg, "connect", side_effect=psycopg.OperationalError("private database URL")), \
             patch.object(storage.sqlite3, "connect") as sqlite:
            with self.assertRaises(psycopg.OperationalError):
                with storage.connection():
                    pass
            sqlite.assert_not_called()

    def test_failed_migration_not_cached_and_configuration_changes_migrate(self):
        factory, _ = self.fake_connection()
        with patch.object(settings, "database_url", "postgresql://synthetic-one"), \
             patch.object(storage.psycopg, "connect", factory), \
             patch.object(storage, "_run_migrations", side_effect=[psycopg.OperationalError("synthetic"), None, None]) as migrate:
            with self.assertRaises(psycopg.OperationalError):
                with storage.connection():
                    pass
            self.assertFalse(storage._migrated_databases)
            with storage.connection():
                pass
            with patch.object(settings, "database_url", "postgresql://synthetic-two"), storage.connection():
                pass
            self.assertEqual(migrate.call_count, 3)

    def test_postgres_history_order_and_account_scope(self):
        factory, raw = self.fake_connection()
        raw.execute.return_value.fetchall.return_value = []
        raw.execute.return_value.fetchone.return_value = None
        with patch.object(settings, "database_url", "postgresql://synthetic"), \
             patch.object(storage.psycopg, "connect", factory), patch.object(storage, "_run_migrations"):
            self.assertEqual(storage.get_user_analyses_history("owner", 7), [])
            self.assertIsNone(storage.get_contract("contract", "owner"))
            self.assertIsNone(storage.get_analysis("analysis", "owner"))
            self.assertIsNone(storage.get_failure("failure", "owner"))
        queries = [(c.args[0], c.args[1]) for c in raw.execute.call_args_list if len(c.args) > 1]
        self.assertIn(("SELECT result_json FROM analyses WHERE user_id=%s ORDER BY storage_sequence DESC LIMIT %s", ("owner", 7)), queries)
        for field in ("source_json", "result_json", "failure_json"):
            self.assertTrue(any(f"SELECT {field}" in q and "user_id=%s" in q and params == ("contract" if field == "source_json" else "analysis" if field == "result_json" else "failure", "owner") for q, params in queries))

    def test_pdf_bytes_pass_to_driver_and_subscription_updates_remain_allowlisted(self):
        factory, raw = self.fake_connection()
        contract = source()
        pdf = b"%PDF-synthetic\x00\xff"
        with patch.object(settings, "database_url", "postgresql://synthetic"), \
             patch.object(storage.psycopg, "connect", factory), patch.object(storage, "_run_migrations"):
            storage.save_contract(contract, pdf, "owner")
            storage.update_subscription("subscription", {"status": "active", "user_id": "attacker", "bad_sql": "ignored"})
        inserts = [c for c in raw.execute.call_args_list if "INSERT INTO contracts" in c.args[0]]
        self.assertEqual(inserts[0].args[1][2], pdf)
        updates = [c for c in raw.execute.call_args_list if c.args[0].startswith("UPDATE subscriptions")]
        self.assertEqual(updates[0].args, ("UPDATE subscriptions SET status = %s WHERE id = %s", ("active", "subscription")))

    def test_postgres_api_errors_are_sanitized_even_in_auth(self):
        with TestClient(app) as client, \
             patch("app.routes.auth.get_user_by_email", side_effect=psycopg.OperationalError("postgresql://private-key@secret-host")):
            response = client.post("/api/auth/login", json={"email": "user@test.invalid", "password": "synthetic-password"})
        self.assertEqual(response.status_code, 503)
        self.assertNotIn("private-key", response.text)
        self.assertNotIn("secret-host", response.text)

    def test_failed_postgres_analysis_save_has_storage_category(self):
        contract = source()
        error = psycopg.OperationalError("private database URL")
        with patch("app.services.contract_analysis.match_policies", side_effect=error), \
             patch("app.services.contract_analysis.save_failure") as save:
            with self.assertRaises(psycopg.OperationalError):
                analyze_contract(contract)
        failure = save.call_args.args[0]
        self.assertEqual(failure.error_category, "storage")
        self.assertEqual(failure.http_status, 503)
        self.assertNotIn("private", failure.message)

    def test_vercel_entrypoint_exports_same_app_and_refuses_ephemeral_sqlite(self):
        path = Path(__file__).resolve().parents[1] / "backend" / "index.py"
        with patch.dict(os.environ, {"VERCEL": "1"}), patch.object(settings, "database_url", ""):
            spec = importlib.util.spec_from_file_location("veritas_vercel_test", path)
            with self.assertRaisesRegex(RuntimeError, "DATABASE_URL"):
                spec.loader.exec_module(importlib.util.module_from_spec(spec))
        with patch.dict(os.environ, {"VERCEL": "1"}), patch.object(settings, "database_url", "postgresql://synthetic"):
            spec = importlib.util.spec_from_file_location("veritas_vercel_test", path)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            self.assertIs(module.app, app)
            with TestClient(module.app) as client:
                self.assertEqual(client.get("/health").status_code, 200)
                self.assertEqual(client.post("/api/analyze", json={"contract_id": "synthetic"}).status_code, 401)

    def test_vercel_configuration_preserves_resources_and_no_secrets(self):
        root = Path(__file__).resolve().parents[1]
        config = json.loads((root / "backend/vercel.json").read_text())
        self.assertEqual(config["functions"]["index.py"]["maxDuration"], 300)
        self.assertIn("app/resources", config["functions"]["index.py"]["includeFiles"])
        self.assertIn(".env", config["functions"]["index.py"]["excludeFiles"])
        frontend = json.loads((root / "frontend/vercel.json").read_text())
        self.assertEqual(frontend["outputDirectory"], "dist")
        self.assertEqual(frontend["installCommand"], "npm ci")
        self.assertNotIn("DATABASE_URL", json.dumps(frontend))


if __name__ == "__main__":
    unittest.main()
